// utils/questions.js — 评估问卷题目库
// 共分5个部分，约28道题

const QUESTIONS = [

  // ─── 第一部分：基本信息（非评分题）───
  {
    id: 'q_basic_01',
    part: 1,
    partTitle: '基本信息',
    type: 'input',
    question: '请告诉我们孩子的名字（昵称即可）',
    placeholder: '例如：小明',
    key: 'childName',
  },
  {
    id: 'q_basic_02',
    part: 1,
    partTitle: '基本信息',
    type: 'number',
    question: '孩子目前的年龄',
    placeholder: '请输入数字，例如：8',
    key: 'childAge',
  },
  {
    id: 'q_basic_03',
    part: 1,
    partTitle: '基本信息',
    type: 'choice',
    question: '孩子目前就读的学段',
    key: 'schoolStage',
    options: [
      { label: '学前/幼儿园', value: 'preschool' },
      { label: '小学（1-6年级）', value: 'primary' },
      { label: '初中（7-9年级）', value: 'middle' },
      { label: '高中（10-12年级）', value: 'high' },
    ],
  },
  {
    id: 'q_basic_04',
    part: 1,
    partTitle: '基本信息',
    type: 'choice',
    question: '孩子目前就读的学校类型',
    key: 'schoolType',
    options: [
      { label: '公立学校', value: 'public' },
      { label: '私立/民办学校', value: 'private' },
      { label: '双语学校', value: 'bilingual' },
      { label: '国际学校', value: 'international' },
    ],
  },
  {
    id: 'q_basic_05',
    part: 1,
    partTitle: '基本信息',
    type: 'choice',
    question: '孩子目前的英语水平如何？（客观评估，非愿望）',
    key: 'englishLevel',
    note: '这直接影响出国路径的可行性评估',
    options: [
      { label: '基础薄弱（难以日常交流）', value: 'weak',    score: 1 },
      { label: '日常交流（能理解常见内容）', value: 'basic',  score: 2 },
      { label: '流畅表达（能上英文课程）',  value: 'good',   score: 3 },
      { label: '接近母语（双语/国际环境）',  value: 'native', score: 4 },
    ],
  },
  {
    id: 'q_basic_06',
    part: 1,
    partTitle: '基本信息',
    type: 'choice',
    question: '孩子目前在班级/年级的学业表现大致属于？',
    key: 'academicTier',
    note: '综合学科成绩的整体判断，不限于某一科',
    options: [
      { label: '中下游（后30%）',   value: 'low',        score: 1 },
      { label: '中等水平（中间段）', value: 'mid',        score: 2 },
      { label: '中上游（前30%）',   value: 'upper_mid',  score: 3 },
      { label: '优秀（年级前10%）', value: 'top',        score: 4 },
    ],
  },

  // ─── 第二部分：多元智能评估（核心）───
  // 每种智能1-2道观察性问题，家长按频率选择
  // 选项：几乎从不(1) / 偶尔(2) / 经常(3) / 几乎总是(4)

  {
    id: 'q_mi_lang_01',
    part: 2,
    partTitle: '多元智能评估',
    intelligence: 'linguistic',
    type: 'frequency',
    question: '孩子喜欢讲故事、编故事，或者讲笑话给别人听',
    key: 'mi_linguistic_1',
  },
  {
    id: 'q_mi_lang_02',
    part: 2,
    partTitle: '多元智能评估',
    intelligence: 'linguistic',
    type: 'frequency',
    question: '孩子喜欢读书、听故事，对文字和语言表现出浓厚兴趣',
    key: 'mi_linguistic_2',
  },
  {
    id: 'q_mi_logic_01',
    part: 2,
    partTitle: '多元智能评估',
    intelligence: 'logical',
    type: 'frequency',
    question: '孩子喜欢数字游戏、逻辑谜题，或者问「为什么」的问题',
    key: 'mi_logical_1',
  },
  {
    id: 'q_mi_logic_02',
    part: 2,
    partTitle: '多元智能评估',
    intelligence: 'logical',
    type: 'frequency',
    question: '孩子做事有条理，喜欢分类整理，对规律和系统感兴趣',
    key: 'mi_logical_2',
  },
  {
    id: 'q_mi_spatial_01',
    part: 2,
    partTitle: '多元智能评估',
    intelligence: 'spatial',
    type: 'frequency',
    question: '孩子喜欢画画、搭积木、拼乐高，对空间和图形有天然兴趣',
    key: 'mi_spatial_1',
  },
  {
    id: 'q_mi_spatial_02',
    part: 2,
    partTitle: '多元智能评估',
    intelligence: 'spatial',
    type: 'frequency',
    question: '孩子能很快记住路线、地图，或者对建筑和设计感兴趣',
    key: 'mi_spatial_2',
  },
  {
    id: 'q_mi_musical_01',
    part: 2,
    partTitle: '多元智能评估',
    intelligence: 'musical',
    type: 'frequency',
    question: '孩子对音乐、节奏敏感，喜欢哼歌、跟着音乐打拍子',
    key: 'mi_musical_1',
  },
  {
    id: 'q_mi_bodily_01',
    part: 2,
    partTitle: '多元智能评估',
    intelligence: 'bodily',
    type: 'frequency',
    question: '孩子动手能力强，喜欢做手工、运动，身体协调性好',
    key: 'mi_bodily_1',
  },
  {
    id: 'q_mi_inter_01',
    part: 2,
    partTitle: '多元智能评估',
    intelligence: 'interpersonal',
    type: 'frequency',
    question: '孩子很容易交到朋友，喜欢和别人合作，善于理解他人的感受',
    key: 'mi_interpersonal_1',
  },
  {
    id: 'q_mi_intra_01',
    part: 2,
    partTitle: '多元智能评估',
    intelligence: 'intrapersonal',
    type: 'frequency',
    question: '孩子喜欢独处思考，对自己的感受有清晰的认识，有自己的想法和坚持',
    key: 'mi_intrapersonal_1',
  },
  {
    id: 'q_mi_nature_01',
    part: 2,
    partTitle: '多元智能评估',
    intelligence: 'naturalist',
    type: 'frequency',
    question: '孩子对动植物、自然现象非常感兴趣，喜欢户外探索',
    key: 'mi_naturalist_1',
  },

  // ─── 第三部分：成长型思维评估 ───
  {
    id: 'q_mindset_01',
    part: 3,
    partTitle: '思维模式观察',
    type: 'frequency',
    question: '当孩子遇到很难的题目做不出来，他/她会继续尝试而不是放弃',
    key: 'mindset_persistence',
  },
  {
    id: 'q_mindset_02',
    part: 3,
    partTitle: '思维模式观察',
    type: 'frequency',
    question: '孩子看到别人比自己做得好，会想要向对方学习（而不是感到沮丧或嫉妒）',
    key: 'mindset_learning_from_others',
  },
  {
    id: 'q_mindset_03',
    part: 3,
    partTitle: '思维模式观察',
    type: 'frequency',
    question: '孩子在受到批评后，能够反思并做出调整（而不是辩解或回避）',
    key: 'mindset_feedback',
  },
  {
    id: 'q_mindset_04',
    part: 3,
    partTitle: '思维模式观察',
    type: 'choice',
    question: '当孩子面对一件新的、有挑战的事情时，他/她通常的第一反应是？',
    key: 'mindset_challenge_response',
    options: [
      { label: '兴奋，主动想去尝试', value: 'excited' },
      { label: '谨慎，先观察再决定', value: 'cautious' },
      { label: '担心失败，需要大人鼓励', value: 'anxious' },
      { label: '直接拒绝，不想尝试', value: 'avoids' },
    ],
  },

  // ─── 第四部分：家庭信息 ───
  {
    id: 'q_family_01',
    part: 4,
    partTitle: '家庭背景',
    type: 'choice',
    question: '您（父亲/母亲）的主要职业背景是？',
    key: 'parent_occupation',
    options: [
      { label: '企业管理/高管', value: 'corporate_executive' },
      { label: '创业者/企业主', value: 'entrepreneur' },
      { label: '政府/国有企业', value: 'government' },
      { label: '专业人士（医/律/会计/学者）', value: 'professional' },
      { label: '金融/投资', value: 'finance' },
      { label: '技术/工程', value: 'technology' },
      { label: '贸易/销售', value: 'trade' },
      { label: '其他', value: 'other' },
    ],
  },
  {
    id: 'q_family_02',
    part: 4,
    partTitle: '家庭背景',
    type: 'choice',
    question: '家庭目前所在的城市层级',
    key: 'city_tier',
    options: [
      { label: '北上广深（一线城市）', value: 'tier1' },
      { label: '杭州、成都、武汉等（新一线）', value: 'tier1_5' },
      { label: '二线城市', value: 'tier2' },
      { label: '三线及以下城市', value: 'tier3' },
      { label: '海外', value: 'overseas' },
    ],
  },
  {
    id: 'q_family_03',
    part: 4,
    partTitle: '家庭背景',
    type: 'choice',
    question: '家庭每年可以用于孩子教育的投入大致在哪个区间？（包含学费、培训、活动等所有教育支出）',
    key: 'education_budget',
    options: [
      { label: '5万以内', value: 'under_5w' },
      { label: '5-15万', value: '5_15w' },
      { label: '15-30万', value: '15_30w' },
      { label: '30-60万', value: '30_60w' },
      { label: '60万以上', value: 'over_60w' },
    ],
  },
  {
    id: 'q_family_04',
    part: 4,
    partTitle: '家庭背景',
    type: 'choice',
    question: '您或配偶是否有海外学习或生活经历？',
    key: 'overseas_experience',
    options: [
      { label: '有，本人或配偶有留学经历', value: 'yes_study' },
      { label: '有，曾在海外工作生活', value: 'yes_work' },
      { label: '没有，但家人或朋友有', value: 'network_only' },
      { label: '完全没有海外经历', value: 'none' },
    ],
  },

  // ─── 第五部分：期望与目标 ───
  {
    id: 'q_goal_01',
    part: 5,
    partTitle: '目标与期望',
    type: 'choice',
    question: '您最希望孩子在20-25岁时处于什么状态？（选最接近的一项）',
    key: 'goal_at_25',
    options: [
      { label: '在国内顶尖公司/机构工作，稳定发展', value: 'stable_china' },
      { label: '在海外顶尖公司工作，或在国外定居', value: 'career_overseas' },
      { label: '创业或独立从事某个领域', value: 'entrepreneurship' },
      { label: '继续深造，走学术或研究路线', value: 'academia' },
      { label: '接手家族事业', value: 'family_business' },
      { label: '我希望孩子自己决定，我都支持', value: 'child_decides' },
    ],
  },
  {
    id: 'q_goal_02',
    part: 5,
    partTitle: '目标与期望',
    type: 'choice',
    question: '对于孩子的教育路径，您目前倾向于？',
    key: 'education_path_preference',
    options: [
      { label: '国内高考路线为主', value: 'gaokao' },
      { label: '高中出国留学', value: 'highschool_abroad' },
      { label: '国内读完高中，大学再出国', value: 'university_abroad' },
      { label: '国际学校，保留灵活性', value: 'international_school' },
      { label: '还没想好，希望系统给建议', value: 'undecided' },
    ],
  },
  {
    id: 'q_goal_03',
    part: 5,
    partTitle: '目标与期望',
    type: 'choice',
    question: '在孩子的教育决策中，您最担心的事情是什么？',
    key: 'biggest_concern',
    options: [
      { label: '选错了路径，走弯路浪费时间', value: 'wrong_path' },
      { label: '花了很多钱但效果不好', value: 'poor_roi' },
      { label: '孩子不开心，有心理压力', value: 'mental_health' },
      { label: '跟不上社会变化，未来没竞争力', value: 'future_readiness' },
      { label: '和孩子的意愿冲突，关系变差', value: 'parent_child_conflict' },
    ],
  },
  {
    id: 'q_goal_04',
    part: 5,
    partTitle: '目标与期望',
    type: 'number',
    question: '孩子目前或预估的SAT成绩是多少？（如有ACT请折算，可跳过）',
    placeholder: '例：1350',
    key: 'sat_score_est',
    optional: true,
    note: '用于精准匹配美国大学录取概率，无成绩可跳过，系统会自动估算',
  },
  {
    id: 'q_goal_05',
    part: 5,
    partTitle: '目标与期望',
    type: 'number',
    question: '孩子目前或预估的GPA是多少？（90分≈3.9，85分≈3.7，80分≈3.5）',
    placeholder: '例：3.7',
    key: 'gpa_est',
    optional: true,
    note: '4.0制，无成绩可跳过',
  },
];

// 计算各部分题目范围
const PARTS = [
  { id: 1, title: '基本信息', icon: '👤', color: '#1B6CA8' },
  { id: 2, title: '多元智能评估', icon: '🧠', color: '#2A7A5A' },
  { id: 3, title: '思维模式观察', icon: '💡', color: '#C49A22' },
  { id: 4, title: '家庭背景', icon: '🏡', color: '#5B3A8B' },
  { id: 5, title: '目标与期望', icon: '🎯', color: '#1A3A5C' },
];

// 频率选项（用于frequency类型题目）
const FREQUENCY_OPTIONS = [
  { label: '几乎从不', value: 1, desc: '很少见到这种行为' },
  { label: '偶尔', value: 2, desc: '有时会这样' },
  { label: '经常', value: 3, desc: '比较常见' },
  { label: '几乎总是', value: 4, desc: '这是他/她的典型表现' },
];

module.exports = { QUESTIONS, PARTS, FREQUENCY_OPTIONS };
